# Copyright 2026 Iroiso Ikpokonte
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from typing import Literal, Union, TypedDict, Optional, List, Tuple, Type, Iterable
from cqlalchemy.core.models import CqlProperty, Index

Order = Literal["ASC", "DESC"]
Column = Literal[
    "ascii",
    "bigint",
    "blob",
    "boolean",
    "counter",
    "decimal",
    "double",
    "duration",
    "float",
    "inet",
    "int",
    "smallint",
    "text",
    "time",
    "date",
    "timestamp",
    "timeuuid",
    "tinyint",
    "tuple",
    "uuid",
    "varchar",
    "varint",
    "list<ascii>",
    "list<bigint>",
    "list<blob>",
    "list<boolean>",
    "list<decimal>",
    "list<double>",
    "list<duration>",
    "list<float>",
    "list<inet>",
    "list<int>",
    "list<smallint>",
    "list<text>",
    "list<time>",
    "list<date>",
    "list<timestamp>",
    "list<timeuuid>",
    "list<tinyint>",
    "list<uuid>",
    "list<varchar>",
    "list<varint>",
    "set<ascii>",
    "set<bigint>",
    "set<blob>",
    "set<boolean>",
    "set<decimal>",
    "set<double>",
    "set<duration>",
    "set<float>",
    "set<inet>",
    "set<int>",
    "set<smallint>",
    "set<text>",
    "set<time>",
    "set<date>",
    "set<timestamp>",
    "set<timeuuid>",
    "set<tinyint>",
    "set<uuid>",
    "set<varchar>",
    "set<varint>",
    "map<text,duration>",
    "map<date,double>",
    "map<double,double>",
    "map<boolean,ascii>",
    "map<timestamp,date>",
    "map<decimal,decimal>",
    "map<int,counter>",
    "map<inet,time>",
    "map<date,blob>",
    "map<date,date>",
    "map<int,blob>",
    "map<ascii,inet>",
    "map<time,uuid>",
    "map<counter,bigint>",
    "map<date,ascii>",
    "map<text,text>",
    "map<tinyint,int>",
    "map<duration,tinyint>",
    "map<tinyint,boolean>",
    "map<blob,date>",
    "map<float,duration>",
    "map<smallint,int>",
    "map<timeuuid,ascii>",
    "map<blob,boolean>",
    "map<counter,boolean>",
    "map<decimal,counter>",
    "map<boolean,text>",
    "map<duration,blob>",
    "map<decimal,date>",
    "map<inet,smallint>",
    "map<inet,inet>",
    "map<decimal,int>",
    "map<text,timeuuid>",
    "map<text,uuid>",
    "map<smallint,tinyint>",
    "map<date,inet>",
    "map<float,float>",
    "map<text,time>",
    "map<boolean,boolean>",
    "map<varchar,blob>",
    "map<varint,blob>",
    "map<smallint,decimal>",
    "map<time,varchar>",
    "map<time,varint>",
    "map<inet,bigint>",
    "map<decimal,boolean>",
    "map<float,boolean>",
    "map<timestamp,uuid>",
    "map<uuid,counter>",
    "map<counter,decimal>",
    "map<blob,ascii>",
    "map<uuid,decimal>",
    "map<text,double>",
    "map<duration,uuid>",
    "map<double,date>",
    "map<decimal,ascii>",
    "map<boolean,bigint>",
    "map<duration,ascii>",
    "map<uuid,blob>",
    "map<boolean,int>",
    "map<duration,time>",
    "map<int,timestamp>",
    "map<varchar,varchar>",
    "map<varint,varint>",
    "map<timeuuid,date>",
    "map<decimal,tinyint>",
    "map<tinyint,time>",
    "map<bigint,text>",
    "map<text,varchar>",
    "map<text,varint>",
    "map<timeuuid,smallint>",
    "map<bigint,inet>",
    "map<int,smallint>",
    "map<uuid,date>",
    "map<varchar,time>",
    "map<varint,time>",
    "map<bigint,timeuuid>",
    "map<blob,varchar>",
    "map<blob,varint>",
    "map<time,tinyint>",
    "map<date,counter>",
    "map<inet,duration>",
    "map<blob,uuid>",
    "map<date,boolean>",
    "map<timestamp,timestamp>",
    "map<counter,smallint>",
    "map<tinyint,uuid>",
    "map<inet,boolean>",
    "map<float,tinyint>",
    "map<inet,timestamp>",
    "map<text,decimal>",
    "map<counter,inet>",
    "map<date,timestamp>",
    "map<text,tinyint>",
    "map<double,boolean>",
    "map<text,blob>",
    "map<smallint,time>",
    "map<boolean,uuid>",
    "map<text,inet>",
    "map<date,uuid>",
    "map<counter,time>",
    "map<decimal,timestamp>",
    "map<bigint,blob>",
    "map<ascii,date>",
    "map<timeuuid,uuid>",
    "map<smallint,double>",
    "map<ascii,timeuuid>",
    "map<double,varchar>",
    "map<double,varint>",
    "map<bigint,date>",
    "map<ascii,double>",
    "map<double,counter>",
    "map<smallint,text>",
    "map<int,inet>",
    "map<ascii,bigint>",
    "map<varchar,inet>",
    "map<varint,inet>",
    "map<inet,date>",
    "map<text,timestamp>",
    "map<timeuuid,timeuuid>",
    "map<timeuuid,inet>",
    "map<bigint,decimal>",
    "map<duration,inet>",
    "map<timestamp,decimal>",
    "map<int,varchar>",
    "map<int,varint>",
    "map<text,int>",
    "map<ascii,counter>",
    "map<ascii,boolean>",
    "map<double,tinyint>",
    "map<text,float>",
    "map<timestamp,varchar>",
    "map<timestamp,varint>",
    "map<double,int>",
    "map<varchar,timeuuid>",
    "map<varint,timeuuid>",
    "map<bigint,boolean>",
    "map<boolean,float>",
    "map<varchar,date>",
    "map<varint,date>",
    "map<ascii,float>",
    "map<tinyint,timestamp>",
    "map<uuid,ascii>",
    "map<decimal,uuid>",
    "map<inet,decimal>",
    "map<bigint,double>",
    "map<date,float>",
    "map<ascii,time>",
    "map<inet,float>",
    "map<time,ascii>",
    "map<tinyint,varchar>",
    "map<varchar,float>",
    "map<timestamp,boolean>",
    "map<boolean,timeuuid>",
    "map<float,bigint>",
    "map<int,int>",
    "map<bigint,varchar>",
    "map<counter,int>",
    "map<timestamp,counter>",
    "map<inet,ascii>",
    "map<date,duration>",
    "map<counter,text>",
    "map<tinyint,timeuuid>",
    "map<double,ascii>",
    "map<tinyint,duration>",
    "map<timestamp,timeuuid>",
    "map<text,smallint>",
    "map<inet,double>",
    "map<double,text>",
    "map<float,time>",
    "map<double,duration>",
    "map<timeuuid,tinyint>",
    "map<blob,counter>",
    "map<float,decimal>",
    "map<smallint,float>",
    "map<bigint,float>",
    "map<blob,timeuuid>",
    "map<tinyint,counter>",
    "map<date,tinyint>",
    "map<double,timestamp>",
    "map<time,blob>",
    "map<blob,decimal>",
    "map<bigint,timestamp>",
    "map<float,double>",
    "map<duration,text>",
    "map<inet,blob>",
    "map<duration,bigint>",
    "map<uuid,int>",
    "map<boolean,varchar>",
    "map<uuid,timeuuid>",
    "map<duration,date>",
    "map<varchar,tinyint>",
    "map<duration,smallint>",
    "map<varchar,timestamp>",
    "map<decimal,bigint>",
    "map<int,tinyint>",
    "map<time,decimal>",
    "map<counter,duration>",
    "map<counter,blob>",
    "map<decimal,float>",
    "map<smallint,timestamp>",
    "map<duration,varchar>",
    "map<smallint,boolean>",
    "map<inet,int>",
    "map<bigint,time>",
    "map<date,int>",
    "map<timeuuid,duration>",
    "map<boolean,date>",
    "map<timestamp,duration>",
    "map<time,int>",
    "map<time,date>",
    "map<tinyint,tinyint>",
    "map<bigint,uuid>",
    "map<float,varchar>",
    "map<smallint,timeuuid>",
    "map<counter,ascii>",
    "map<timeuuid,text>",
    "map<decimal,varchar>",
    "map<bigint,ascii>",
    "map<duration,duration>",
    "map<float,date>",
    "map<inet,uuid>",
    "map<timeuuid,float>",
    "map<blob,duration>",
    "map<float,smallint>",
    "map<boolean,smallint>",
    "map<decimal,smallint>",
    "map<bigint,tinyint>",
    "map<counter,date>",
    "map<float,blob>",
    "map<smallint,duration>",
    "map<decimal,double>",
    "map<tinyint,decimal>",
    "map<duration,float>",
    "map<time,counter>",
    "map<double,decimal>",
    "map<varchar,ascii>",
    "map<date,time>",
    "map<tinyint,ascii>",
    "map<int,double>",
    "map<float,inet>",
    "map<time,timeuuid>",
    "map<int,uuid>",
    "map<int,date>",
    "map<bigint,duration>",
    "map<inet,timeuuid>",
    "map<timestamp,ascii>",
    "map<int,time>",
    "map<float,counter>",
    "map<duration,int>",
    "map<tinyint,inet>",
    "map<tinyint,float>",
    "map<tinyint,bigint>",
    "map<blob,float>",
    "map<uuid,double>",
    "map<varchar,decimal>",
    "map<boolean,counter>",
    "map<date,timeuuid>",
    "map<smallint,ascii>",
    "map<smallint,varchar>",
    "map<duration,decimal>",
    "map<time,time>",
    "map<smallint,inet>",
    "map<varchar,boolean>",
    "map<uuid,tinyint>",
    "map<timestamp,time>",
    "map<boolean,time>",
    "map<time,double>",
    "map<boolean,duration>",
    "map<blob,tinyint>",
    "map<timeuuid,decimal>",
    "map<decimal,text>",
    "map<duration,double>",
    "map<timestamp,blob>",
    "map<ascii,uuid>",
    "map<bigint,int>",
    "map<timeuuid,int>",
    "map<timeuuid,double>",
    "map<int,boolean>",
    "map<double,inet>",
    "map<int,bigint>",
    "map<decimal,blob>",
    "map<uuid,uuid>",
    "map<int,timeuuid>",
    "map<decimal,timeuuid>",
    "map<varchar,int>",
    "map<blob,text>",
    "map<float,int>",
    "map<time,duration>",
    "map<int,decimal>",
    "map<timestamp,text>",
    "map<timeuuid,boolean>",
    "map<int,text>",
    "map<ascii,int>",
    "map<counter,timestamp>",
    "map<float,timestamp>",
    "map<blob,blob>",
    "map<ascii,duration>",
    "map<smallint,counter>",
    "map<boolean,timestamp>",
    "map<counter,double>",
    "map<varchar,double>",
    "map<inet,varchar>",
    "map<timestamp,tinyint>",
    "map<boolean,double>",
    "map<int,duration>",
    "map<ascii,ascii>",
    "map<uuid,inet>",
    "map<inet,text>",
    "map<timeuuid,counter>",
    "map<text,bigint>",
    "map<timestamp,bigint>",
    "map<timestamp,float>",
    "map<varchar,counter>",
    "map<date,smallint>",
    "map<decimal,duration>",
    "map<float,text>",
    "map<ascii,smallint>",
    "map<time,text>",
    "map<duration,counter>",
    "map<boolean,blob>",
    "map<boolean,inet>",
    "map<blob,bigint>",
    "map<smallint,bigint>",
    "map<bigint,bigint>",
    "map<counter,counter>",
    "map<tinyint,date>",
    "map<uuid,bigint>",
    "map<double,time>",
    "map<tinyint,blob>",
    "map<uuid,duration>",
    "map<timeuuid,time>",
    "map<text,ascii>",
    "map<blob,timestamp>",
    "map<counter,tinyint>",
    "map<decimal,inet>",
    "map<uuid,float>",
    "map<int,ascii>",
    "map<time,float>",
    "map<ascii,varchar>",
    "map<tinyint,double>",
    "map<float,timeuuid>",
    "map<tinyint,smallint>",
    "map<timeuuid,timestamp>",
    "map<duration,boolean>",
    "map<blob,double>",
    "map<timestamp,int>",
    "map<varchar,smallint>",
    "map<double,float>",
    "map<tinyint,text>",
    "map<double,uuid>",
    "map<text,date>",
    "map<inet,counter>",
    "map<varchar,bigint>",
    "map<varchar,text>",
    "map<ascii,text>",
    "map<uuid,timestamp>",
    "map<timestamp,inet>",
    "map<bigint,smallint>",
    "map<counter,varchar>",
    "map<double,blob>",
    "map<smallint,blob>",
    "map<blob,smallint>",
    "map<timeuuid,varchar>",
    "map<uuid,text>",
    "map<uuid,time>",
    "map<duration,timeuuid>",
    "map<text,boolean>",
    "map<double,bigint>",
    "map<timeuuid,blob>",
    "map<time,bigint>",
    "map<ascii,timestamp>",
    "map<blob,inet>",
    "map<time,timestamp>",
    "map<boolean,tinyint>",
    "map<float,ascii>",
    "map<date,bigint>",
    "map<boolean,decimal>",
    "map<text,counter>",
    "map<ascii,blob>",
    "map<ascii,tinyint>",
    "map<int,float>",
    "map<blob,int>",
    "map<counter,timeuuid>",
    "map<uuid,smallint>",
    "map<time,smallint>",
    "map<date,text>",
    "map<blob,time>",
    "map<counter,uuid>",
    "map<time,boolean>",
    "map<double,timeuuid>",
    "map<timeuuid,bigint>",
    "map<counter,float>",
    "map<decimal,time>",
    "map<duration,timestamp>",
    "map<timestamp,smallint>",
    "map<bigint,counter>",
    "map<double,smallint>",
    "map<inet,tinyint>",
    "map<date,decimal>",
    "map<smallint,date>",
    "map<float,uuid>",
    "map<varchar,uuid>",
    "map<ascii,decimal>",
    "map<uuid,boolean>",
    "map<smallint,uuid>",
    "map<time,inet>",
    "map<uuid,varchar>",
    "map<varchar,duration>",
    "map<smallint,smallint>",
    "map<date,varchar>",
    "map<timestamp,double>",
]


class FieldDict(TypedDict):
    """Arguments for Table Field"""

    name: str
    type: Union[Column, CqlProperty, Type[CqlProperty]]
    primary: Optional[bool] = False
    key: Optional[bool] = False
    composite: Optional[List[str]] = []
    order: Optional[Order] = None
    static: Optional[bool] = False
    index: Optional[bool | Index] = False


class TableDict(TypedDict):
    """Arguments for Table Operation"""

    keyspace: str
    name: str
    accord: Optional[bool] = True
    columns: Iterable[FieldDict]
    expires: Optional[int] = 0
    comment: Optional[str] = ""


class ColumnDict(TypedDict):
    """Arguments for Column Operation"""

    keyspace: str
    table: str
    name: str
    type: Union[Column, CqlProperty]
    static: Optional[bool] = None


class DropDict(TypedDict):
    """Arguments for Drop Operation"""

    target: str = Literal["Keyspace", "Table", "Column", "Index"]
    keyspace: str
    table: str
    column: Optional[str] = None
    index: Optional[str] = None


class AlterDict(TypedDict):
    """Arguments for Alter Operation"""

    keyspace: Optional[str] = None
    table: Optional[str] = None
    options: Optional[dict] = None


class IndexDict(TypedDict):
    """Arguments for Index Operation"""

    keyspace: str
    table: str
    column: str
    name: Optional[str] = None
    type: Index


class RenameDict(TypedDict):
    """Arguments for a Rename Operation"""

    keyspace: str
    table: str
    column: str
    to: str


class TruncateDict(TypedDict):
    """Arguments for a Truncate Operation"""

    keyspace: str
    table: str
